openapi: 3.0.1
info:
  title: ManagementResourceApi
  description: Sample taken from random parts of the FeatureHub-IO (https://featurehub.io) API
  version: "1.1.1"
paths:
  /file-upload:
    post:
      tags:
        - FileService
      summary: Upload a file
      operationId: uploadFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                  format: binary
                effectiveDate:
                  type: string
                submittedBy:
                  type: string
      responses:
        200:
          description: File uploaded
